### ISSUE TITLE
Zombies sutter

### ISSUE THREAD

**Issue by NikkMann** [theletterjwithadot/Ultimate-Config-for-L4D2#1]
Like the title, using the ultimate cfg, zombies now stutter around when they move. Happens in singleplayer too.
Not using any addons.
Running on a rtx 3090 so my rig isnt the issue.

**Comment by NikkMann** [comment]
Also, not using any addons.
Zombies will sometimes randomly be completely black too.

**Comment by NikkMann** [comment]
I've narrowed it down to being caused by the config_custom.cfg

**Comment by NikkMann** [comment]
Figured out it was being caused by lerp 0. commenting it out fixed it.

**Comment by theletterjwithadot** [comment]
I'm guessing you're having this issue on Valve servers, correct?

If you're playing on Valve servers mainly, you can comment out the following lines in config_custom.cfg

```
//# Set Lerp
lerp0

//# Set Rates
rate100

//# Set Interp
interp0
```

_Cheers!_
