### ISSUE TITLE
net_splitpacket_maxrate

### ISSUE THREAD

**Issue by 2x9Mon** [theletterjwithadot/Ultimate-Config-for-L4D2#10]
Why is "net_splitpacket_maxrate" CVAR in your network config set to "50000"? The client-side value will always be restricted to 30k, unless [this](https://github.com/ValveSoftware/Source-1-Games/issues/6054) gets resolved

**Comment by theletterjwithadot** [comment]
You are absolutely right. There is no point setting it to 50000 because it will still cap at 30000.
Thank you for pointing this out!

I'll make the change in a bit!
