### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by HairyMilkshakes** [theletterjwithadot/Ultimate-Config-for-L4D2#3]
Hi, couldn't find any update instructions on what files to keep when you release new updates. What files do I need to retain when I drag/drop to update?

**Comment by theletterjwithadot** [comment]
Any changes that you want to make to the config should be inside config_custom.cfg

So when you update the config files, just do not overwrite config_custom.cfg file and you should be good

I realized I removed the part in the README that explains this, I'll add it back soon

_Cheers!_

**Comment by HairyMilkshakes** [comment]
Thank you!
