### ISSUE TITLE
License/Copyright Issue

### ISSUE THREAD

**Issue by rokkitlawnchair** [theletterjwithadot/Ultimate-Config-for-L4D2#5]
Hi there,

you can not license code under GPL3 if it's not written by yourself. And a lot of people would be happy if you would give them credits for their work.

Regards
=[SFS]= def+1 -TPF- a.k.a. =[SFS]= rokkit lawnchair -TPF-

**Comment by rokkitlawnchair** [comment]
Hi, sorry to bother again - maybe my wording was not clear enough. Code that you only reformatted but did not write yourself, you cannot put under a license, no matter which license it is. And removing attributions to contributors is really not nice.

Regards
=[SFS]= def+1 -TPF- a.k.a. =[SFS]= rokkit lawnchair -TPF-

**Comment by theletterjwithadot** [comment]
Honestly, I'm uncertain what you're after, but I want you to know I'm merely sharing this for others to use if they want to.

I'm not generating any revenue from this if you're looking for a share.

Most of the codes in this config are found in many sites and from various people. Everyone maintains their own version, and it all does look the same. It's impossible to identify the original author, with all the codes looking similar. I'm not looking to start a   crediting war with anyone.

I'm not active in this game as I used to be, nor am I actively updating this config.

Furthermore, I also do not quite understand why you're stating I only “reformatted but did not write” when all I did was Google the relevant vars to understand what they do and put them in a config file in my own format that I utilize for my other programming scripts too.

> a lot of people would be happy if you would give them credits for their work

Do enlighten me with whom these people are, and I will happily credit them if that's what brings them happiness.

Cheers.
J.

**Comment by rokkitlawnchair** [comment]
Hello J.,

sorry for the late answer.

When I've started to "compile" (the code was partly self written and partly taken from other coders/scripts) the SFS autoexec back in 2009 and even earlier an autoexec for TFC back in 1999, I've been confronted with the same problems regarding licencing and copyright as your Project is facing now.

In the US and (I believe) most of the rest of the world, any work is protected by copyright as soon as it is created. Even if the author hasn't registered it for copyright protection - see [Copyright.gov - FAQ - General](https://copyright.gov/help/faq/faq-general.html#mywork). Only the original author/s can waive his/her copyright and for example put his/her work under a certain license. I am not a lawyer, but that's how I have understand how this kind of stuff is working.

In open source projects like e.g. Debian GNU/Linux, there are [Contributor License Agreements](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to take care of licensing/copyright for contributed code. Noone can contribute without giving the project permission to license and/or redistribute what he/she has contributed.

In case of your project - it contains obviously code from other programmers for which the copyright/license status is at least unclear - you IMO don't have the necessary rights/licenses to put the code collection you compiled under any license. And for code written by myself that you used, I can tell you that for sure. Licensing your compilation and my code contained in it is not possible from a legal point of view.

But I don't mind if you use/redistribute my code (as in I give you permission to do so) **if you list me as a contributor** - In [my autoexec I have tried to list the authors of specific scripts](https://codeberg.org/rokkitlawnchair/sfs-l4d-l4d2-autoexec-official/src/branch/master/autoexec.cfg), maybe you can use it for putting reference to contributors of specific code parts into your compilation?

Regards
=[SFS]= def+1 -TPF- a.k.a. =[SFS]= rokkit lawnchair -TPF-

**Comment by theletterjwithadot** [comment]
Sorry it took me awhile to get back on this.
I have done what was needed.
I hope we can rest this issue now.

Cheers.
J.
