### ISSUE TITLE
Brightness issue

### ISSUE THREAD

**Issue by CZTeo** [theletterjwithadot/Ultimate-Config-for-L4D2#6]
The game is very dark whenever switched out of Fullscreen mode and the game won't let me change the brightness either.is this a known problem with the game or it's related to Cfg?

**Comment by theletterjwithadot** [comment]
It's a known issue with this game.

You can use either Nvidia Freestyle (ALT + F3) or ReShade to get the required brightness on Windowed mode.

Cheers,
J.

**Comment by CZTeo** [comment]
thank you for the fast response J.Cheers.
