### ISSUE TITLE
Not a fan of the new chat font, which .apk do I delete?

### ISSUE THREAD

**Issue by HairyMilkshakes** [theletterjwithadot/Ultimate-Config-for-L4D2#8]
Per title, thanks.

**Comment by theletterjwithadot** [comment]
Hi HairyMilkshakes,

I'm sorry that the new VPKs aren't to your liking.
All the VPKs in addons folder are with the chat font so you will have to delete them all from addons folder.

For the previous version (chat font not touched), you can download them from [this commit](https://github.com/theletterjwithadot/Ultimate-Config-for-L4D2/tree/e1074e1bded12d82514341c9858eed17f9d17164/addons).

Cheers!
J.

**Comment by HairyMilkshakes** [comment]
Maybe it'd be a good idea to let people pick and choose? I liked the old CSGO fonts.

**Comment by theletterjwithadot** [comment]
Yeap, I'll do that soon! Thank you for the feedback!

Cheers!
J.

**Comment by theletterjwithadot** [comment]
Completed in https://github.com/theletterjwithadot/Ultimate-Config-for-L4D2/commit/dcf0fd97f109a1b497ec8b388b493f74e209affe
