### ISSUE TITLE
Can't connect to any servers with this config enabled

### ISSUE THREAD

**Issue by HairyMilkshakes** [theletterjwithadot/Ultimate-Config-for-L4D2#9]
Ever since they released this update: https://steamcommunity.com/games/L4D2/announcements/detail/4352250327663410167?snr=2___

I've been having issues connecting to all servers including official Valve ones. Deleting the /cfg folder and verifying the game files allows me to do it again so I am pretty sure it's this config.

**Comment by theletterjwithadot** [comment]
I've played two games after the update without any issues. I tested the config without my custom changes, and it works on both my servers and Valve servers. Some friends I play with also use this config and haven't had any problems.

Have you changed or added anything to the config?

**Comment by HairyMilkshakes** [comment]
Very odd, it seems to have just stopped working for me, nothing changed. I will reinstall it and come back.

**Comment by theletterjwithadot** [comment]
Do you see anything in the Console when the issue happens?

**Comment by HairyMilkshakes** [comment]
Didn't throw any errors, no. Trying now.

**Comment by HairyMilkshakes** [comment]
Seems to be working again, had to execute exec config_default.cfg; exec autoexec.cfg again.
